# To run test:
# windmill firefox http://localhost:8000 test=person_contacts/windmill.py
# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient


def test_recordingSuite0():
    client = WindmillTestClient(__name__)

    client.click(link=u'Edit contacts page')
    client.waits.forPageLoad(timeout=u'20000')
    client.type(text=u'brabadu', id=u'id_username')
    client.type(text=u'190888', id=u'id_password')
    client.click(value=u'login')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', id=u'id_birth_date')
    client.click(id=u'id_birth_date')
    client.asserts.assertNode(id=u'ui-datepicker-div')
